# Generated by Django 5.0.7 on 2024-08-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'hod'), (2, 'staff'), (3, 'student')], default=1, max_length=56),
        ),
    ]
